apiVersion: v1
kind: Service
metadata:
  name: kargo-demo
  namespace: kargo-demo-prod-thn
spec:
  type: NodePort
  selector:
    app: kargo-demo
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
    nodePort: 30082  # Unique for test
